# Global configuration
debug = true
logLevel = "DEBUG"

# Web configuration backend
[web]
address = ":8080"

# Entrypoints
defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

# Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "sophia.events"
watch = true
swarmmode = true
exposedbydefault = false

# Let's Encrypt configuration
[acme]
email = "admin@sophia.events"
storageFile = "acme.json"
entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"
[[acme.domains]]
   main = "sophia.events"
   san = ["www.sophia.events"]
