version: '3.4'
services:
   proxy:
     image: traefik:1.5.0
     configs:
     - source: traefik
       target: /etc/traefik/traefik.toml
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     deploy:
       restart_policy:
         condition: on-failure
   www:
     image: lucj/sophia.events
     deploy:
       restart_policy:
         condition: on-failure
configs:
  traefik:
    file: ./tls/traefik.toml
