version: '3.4'
services:
   proxy:
     image: traefik:1.5.0
     configs:
     - source: traefik
       target: /etc/traefik/traefik.toml
   www:
     image: lucj/www.sophia.events
     ports:
     - 8080:80
   api:
     image: lucj/api.sophia.events
     ports:
     - 8081:3000
   db:
     image: mongo:3.6
configs:
  traefik:
    file: ./conf/traefik.toml
