version: '3.4'
services:
  proxy:
    image: traefik:1.5.1
    configs:
    - source: traefik
      target: /etc/traefik/traefik.toml
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - 80:80
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
  www:
    image: lucj/sophia.events
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:sophia.events"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.contentTypeNosniff=true" 
      restart_policy:
        condition: on-failure
configs:
  traefik:
    file: ./proxy/http.toml
