version: '3.4'
services:
   proxy:
     image: traefik:1.5.0
     configs:
     - source: traefik
       target: /etc/traefik/traefik.toml
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     deploy:
       restart_policy:
         condition: on-failure
   www:
     image: lucj/sophia.events
     deploy:
       labels:
       - "traefik.enable=true"
       - "traefik.frontend.rule=Host:sophia.events"
       - "traefik.frontend.entryPoints=http,https"
       - "traefik.port=80"
       - "traefik.web.frontend.rule=Host:sophia.events"
       - "traefik.web.port=80"
       restart_policy:
         condition: on-failure
configs:
  traefik:
    file: ./tls/traefik.toml
