# Entrypoints
defaultEntryPoints = ["http"]

# Global configuration
debug = true
logLevel = "DEBUG"

# Web configuration backend
[api]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"

# Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "sophia.events"
watch = true
swarmmode = true
exposedbydefault = false
